FROM ubuntu:xenial

MAINTAINER Dongjun, Lee

ADD build-global.sh /root/build-global.sh

# Ubuntu Xenial docker image doesn't have sudo installed
RUN apt-get update && apt-get install -qqy sudo && rm -rf /var/lib/apt/lists/*
RUN /bin/bash -x /root/build-global.sh
